// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen 1.5.1

#ifndef _lcmgentypes_example_valid_t_h
#define _lcmgentypes_example_valid_t_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _lcmgentypes_example_valid_t lcmgentypes_example_valid_t;
struct _lcmgentypes_example_valid_t
{
    int64_t    timestamp;

    /**
     * LCM Type: double[3]
     */
    double     position[3];

    /**
     * LCM Type: double[4]
     */
    double     orientation[4];
    int32_t    num_ranges;

    /**
     * LCM Type: int16_t[num_ranges]
     */
    int16_t    *ranges;

    /**
     * LCM Type: string
     */
    char*      name;
    int8_t     enabled;
};

/**
 * Create a deep copy of a lcmgentypes_example_valid_t.
 * When no longer needed, destroy it with lcmgentypes_example_valid_t_destroy()
 */
lcmgentypes_example_valid_t* lcmgentypes_example_valid_t_copy(const lcmgentypes_example_valid_t* to_copy);

/**
 * Destroy an instance of lcmgentypes_example_valid_t created by lcmgentypes_example_valid_t_copy()
 */
void lcmgentypes_example_valid_t_destroy(lcmgentypes_example_valid_t* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _lcmgentypes_example_valid_t_subscription_t lcmgentypes_example_valid_t_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * lcmgentypes_example_valid_t is received.
 */
typedef void(*lcmgentypes_example_valid_t_handler_t)(
    const lcm_recv_buf_t *rbuf, const char *channel,
    const lcmgentypes_example_valid_t *msg, void *userdata);

/**
 * Publish a message of type lcmgentypes_example_valid_t using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int lcmgentypes_example_valid_t_publish(lcm_t *lcm, const char *channel, const lcmgentypes_example_valid_t *msg);

/**
 * Subscribe to messages of type lcmgentypes_example_valid_t using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is
 *     received. This function is invoked by LCM during calls to lcm_handle()
 *     and lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
lcmgentypes_example_valid_t_subscription_t* lcmgentypes_example_valid_t_subscribe(
    lcm_t *lcm, const char *channel, lcmgentypes_example_valid_t_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by lcmgentypes_example_valid_t_subscribe()
 */
int lcmgentypes_example_valid_t_unsubscribe(lcm_t *lcm, lcmgentypes_example_valid_t_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int lcmgentypes_example_valid_t_subscription_set_queue_capacity(
    lcmgentypes_example_valid_t_subscription_t* subs, int num_messages);

/**
 * Encode a message of type lcmgentypes_example_valid_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to lcmgentypes_example_valid_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int lcmgentypes_example_valid_t_encode(void *buf, int offset, int maxlen, const lcmgentypes_example_valid_t *p);

/**
 * Decode a message of type lcmgentypes_example_valid_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with lcmgentypes_example_valid_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int lcmgentypes_example_valid_t_decode(const void *buf, int offset, int maxlen, lcmgentypes_example_valid_t *msg);

/**
 * Release resources allocated by lcmgentypes_example_valid_t_decode()
 * @return 0
 */
int lcmgentypes_example_valid_t_decode_cleanup(lcmgentypes_example_valid_t *p);

/**
 * Check how many bytes are required to encode a message of type lcmgentypes_example_valid_t
 */
int lcmgentypes_example_valid_t_encoded_size(const lcmgentypes_example_valid_t *p);

// LCM support functions. Users should not call these
int64_t __lcmgentypes_example_valid_t_get_hash(void);
uint64_t __lcmgentypes_example_valid_t_hash_recursive(const __lcm_hash_ptr *p);
int __lcmgentypes_example_valid_t_encode_array(
    void *buf, int offset, int maxlen, const lcmgentypes_example_valid_t *p, int elements);
int __lcmgentypes_example_valid_t_decode_array(
    const void *buf, int offset, int maxlen, lcmgentypes_example_valid_t *p, int elements);
int __lcmgentypes_example_valid_t_decode_array_cleanup(lcmgentypes_example_valid_t *p, int elements);
int __lcmgentypes_example_valid_t_encoded_array_size(const lcmgentypes_example_valid_t *p, int elements);
int __lcmgentypes_example_valid_t_clone_array(const lcmgentypes_example_valid_t *p, lcmgentypes_example_valid_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
